---
title: "Experiment report"
author: "Dusselier Group"
output:
  html_document:
    toc: true
    toc_float: true
params:
  bd: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F)
pacman::p_load(reactable)
```

```{r}
custom_reactable <- function(bd, ...){
  reactable(
    bd,
    defaultColDef = colDef(
      align = "center",
      headerStyle = list(background = "#f7f7f8")), 
    defaultPageSize = 10, onClick = 'select',
    bordered = T, highlight = T, resizable = T, showSortable = T,
    ...
  )
}
```


## Experiment description

```{r}
params$bd %>%
  slice_head(n = 1, by = event) %>%
      select(event, date_time, name, time_duration) %>%
      custom_reactable(
        columns = list(
          event = colDef(name = 'Event', width = 100),
          date_time = colDef(name = 'Start time', width = 200),
          name = colDef(name = 'Event name', minWidth = 200),
          time_duration = colDef(name = 'Duration', width = 100)
        ), selection = 'single'
      )
```

## Quality control {.tabset .tabset-pills}

### Flows

```{r}
params$bd %>% 
  summarise(across(.cols = c(2, 4, 6, 8),
                   .fn = \(x) round(sum(x)/n(), 1)),
            .by = event) %>%
  select(-1) %>%
  rowwise() %>%
  mutate(total = sum(fi_110, fi_120, fi_130, fi_140)) %>%
  custom_reactable(
    columns = list(
      fi_110 = colDef(name = 'Air (mL/min)'),
      fi_120 = colDef(name = 'Carbon dioxide (mL/min)'),
      fi_130 = colDef(name = 'Argon / Propane (mL/min)'),
      fi_140 = colDef(name = 'Nitrogen (mL/min)'),
      total = colDef(name = 'Total flow (mL/min)')
    ), 
  )
```

### Temperature

```{r}
params$bd %>%
  summarise(name = name[1],
            rate = diff(tic_300_pv) %>% mean(na.rm = T) ,
            mean_measure = mean(tic_300_pv),
            mean_set = mean(tic_300_sp),
            mean_r1 = mean(te_310),
            mean_r2 = mean(te_320),
            diff = list(tic_300_pv - te_320),
            .by = event)  %>%
  select(-1) %>%
  mutate(across(.cols = 2:6, .fns = ~round(.x, 1))) %>%
  custom_reactable(
    columns = list(
      name = colDef(name = 'Event', minWidth = 120),
      rate = colDef(name = 'Rate of change'),
      mean_measure = colDef(name = 'Avg. measured'),
      mean_set = colDef(name = 'Avg. setted'),
      mean_r1 = colDef(name = 'Avg. Reactor 1'),
      mean_r2 = colDef(name = 'Avg. Reactor 2'),
      diff = colDef(name = 'Temperature difference',
                    cell = react_sparkline(., show_area = T, decimals = 2,
                                           line_color = 'darkblue'))),
    rowStyle = JS("function(rowInfo) { return { height: '50px' }}")
  )
```

### Pressure

```{r}
params$bd %>%
  summarise(name = name[1],
                mean_set = mean(p_set),
                mean_r1 = mean(pt_310),
                mean_r2 = mean(pt_320),
                delta = mean_r1 - mean_r2,
                .by = event) %>%
      select(-1) %>% 
      mutate(across(.cols = 2:5, .fns = ~round(.x, 1))) %>%
      custom_reactable(
        columns = list(
          name = colDef(name = 'Event', minWidth = 150),
          mean_set = colDef(name = 'Avg. setted', minWidth = 80),
          mean_r1 = colDef(name = 'Avg. Reactor 1', minWidth = 80),
          mean_r2 = colDef(name = 'Avg. Reactor 2', minWidth = 80),
          delta = colDef(name = 'Delta of pressure', minWidth = 80)
        )
      )
```

