#' The application server-side
#'
#' @description Defines the server-side logic for the Shiny application. This includes
#' managing reactive values, handling user inputs, processing data, and generating outputs.
#'
#' @param input List of inputs from the UI, automatically generated by Shiny.
#' @param output List of outputs to be rendered in the UI, automatically generated by Shiny.
#' @param session The Shiny session object, used for managing the session state.
#'
#' @details
#' The server logic performs the following tasks:
#' - Initializes reactive values (`app_state`) to store application-wide data.
#' - Observes and updates the state of the application based on user inputs and data changes.
#' - Handles file selection and directory parsing using `shinyFiles`.
#' - Loads and processes data files (`R.xlsx`, `GC.txt`, `MS.dat`) using custom functions (`load_file`, `load_gc`, `load_ms`).
#' - Filters and processes the experimental database (`bd`) based on user-defined criteria.
#' - Manages server-side logic for individual modules.
#' - Generates a downloadable report (`report.html`) using `quarto_render`.
#' - Implements a timeout mechanism to monitor session activity.
#'
#' @return None. This function is called internally by the Shiny framework to run the server logic.
#'
#' @importFrom shiny reactiveValues observe observeEvent reactive req renderText downloadHandler reactiveTimer eventReactive
#' @importFrom shinyFiles shinyDirChoose parseDirPath getVolumes
#' @importFrom fs path_home path
#' @importFrom dplyr filter mutate left_join
#' @importFrom quarto quarto_render
#' @importFrom magrittr %>%
#'
#' @noRd

app_server <- function(input, output, session) {
  app_state <- reactiveValues()

  observe({
    app_state$df <- df
    app_state$bd <- bd
    app_state$gc <- gc
    app_state$ms <- ms
    app_state$path <- path_files
    app_state$setting <- setting
    app_state$comment <- comment
  })

  volumes <- c(Home = path_home(), getVolumes()())
  shinyDirChoose(input, "directory", roots = volumes)

  path_files <- eventReactive(input$directory, {
    parseDirPath(volumes, input$directory)
  })

  output$dir_header <- renderText({
    path_files() %>%
      as.character %>%
      strsplit('/') %>%
      unlist %>%
      {
        paste("Folder:", .[length(.)])
      }
  })

  df <- reactive({
    req(path_files())
    tryCatch(
      {
        path(path_files(), "R.xlsx") %>% load_file
      },
      error = function(e) NULL
    )
  })

  bd <- reactive({
    tryCatch(
      {
        df() %>% filter(n >= input$log_events)
      },
      error = function(e) NULL
    )
  })

  gc <- reactive({
    req(path_files())
    tryCatch(
      {
        path(path_files(), "GC.txt") %>% load_gc(bd = bd())
      },
      error = function(e) NULL
    )
  })

  ms <- reactive({
    req(path_files())
    tryCatch(
      {
        path(path_files(), "MS.dat") %>% load_ms(bd = bd())
      },
      error = function(e) NULL
    )
  })

  ## Páginas -------------------------------------------------------------------

  setting <- mod_reaction_server('reaction')
  catalyst_char <- mod_catalyst_server('catalyst')
  comment <- mod_log_server('log', app_state)
  mod_quality_server('quality', app_state)
  mod_raw_server('raw', app_state)
  chemometric <- mod_chemometrics_server('chem', app_state)

  observe({
    app_state$chem_values <- chemometric$chem_values
    app_state$molar_flow <- chemometric$molar_flow
    app_state$conversion <- chemometric$conversion
    app_state$mass_balance <- chemometric$mass_balance
    app_state$boxplot <- chemometric$boxplot
    app_state$material <- catalyst_char$material
    app_state$preparation <- catalyst_char$preparation
    app_state$cc <- catalyst_char$cc
    app_state$fcc <- catalyst_char$fcc
    app_state$scc <- catalyst_char$scc
  })

  ### Reporte -------------------------------------------------------------------

  output$report <- downloadHandler(
    filename = "report.html",
    content = function(file) {
      tempReport <- file.path(tempdir(), "report.qmd")
      file.copy("report.qmd", tempReport, overwrite = TRUE)

      quarto_render(
        input = tempReport,
        execute_params = list(
          bd = if (is.null(app_state$comment)) {
            bd() %>% mutate(comment = "")
          } else {
            bd() %>% left_join(app_state$comment)
          },
          df = app_state$df,
          gc = app_state$gc,
          ms = tryCatch(
            {
              app_state$ms %>%
                mutate(
                  time_absolute_date_time = as.character(
                    time_absolute_date_time
                  )
                )
            },
            error = function(e) NULL
          ),
          path = app_state$path,
          material = app_state$material,
          preparation = app_state$preparation,
          cc = app_state$cc,
          fcc = app_state$fcc,
          scc = app_state$scc,
          chem_values = app_state$chem_values,
          molar_flow = app_state$molar_flow,
          conversion = app_state$conversion,
          mass_balance = app_state$mass_balance,
          boxplot = app_state$boxplot
        )
      )

      filename <- path() %>%
        as.character %>%
        strsplit('/') %>%
        unlist %>%
        .[length(.)]

      file.copy(
        from = file.path(tempdir(), 'report.html'),
        to = file.path(path(), paste0(filename, '.html'))
      )
    }
  )
}
