name: Release Win Launcher

on:
  push:
    paths:
      - "win-launcher/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        working-directory: ./win-launcher
        run: |
          cargo build --release
          mkdir -p dist
          cp target/release/dashboard-reactor.exe dist/

      - name: Install jq
        run: choco install jq -y

      - name: Get version
        id: get_version
        working-directory: ./win-launcher
        shell: bash
        run: |
          version=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].version')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ steps.get_version.outputs.version }}

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: ./win-launcher/dist/dashboard-reactor.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
